# Generated by Django 2.0.2 on 2018-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=120)),
                ('survey_creation', models.DateField()),
                ('survey_size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Suggestion_Model',
        ),
    ]
