# Generated by Django 2.0.2 on 2018-03-16 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180311_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_model',
            name='survey_description',
            field=models.CharField(default=datetime.datetime(2018, 3, 16, 3, 49, 37, 588925, tzinfo=utc), max_length=240),
            preserve_default=False,
        ),
    ]
