# Generated by Django 2.0.2 on 2018-05-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180419_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey_Model',
        ),
        migrations.AlterField(
            model_name='event_model',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='event_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='event_model',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event_Model'),
        ),
    ]
