# Generated by Django 2.0.2 on 2018-05-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180516_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_model',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat_model',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='chatline_model',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat_Model',
        ),
    ]
